In [11]:
import pandapower as pp
import pandapower.networks as nw
import pandas as pd
from pandapower.timeseries.data_sources.frame_data import DFData
from pandapower.timeseries.output_writer import OutputWriter
from pandapower.control import ConstControl
from pandapower.timeseries.run_time_series import run_timeseries

#create empty net
net = nw.create_cigre_network_mv()

In [12]:
load_shape = pd.read_excel('Loadshape_step_2.xlsx', usecols=[1])

In [13]:
num_hours = len(load_shape)

In [14]:
net.load

,name,bus,p_mw,q_mvar,const_z_percent,const_i_percent,sn_mva,scaling,in_service,type
0,Load R1,1,14.99400,3.044662,0.0,0.0,15.300,1.0,True,wye
1,Load R3,3,0.27645,0.069285,0.0,0.0,0.285,1.0,True,wye
2,Load R4,4,0.43165,0.108182,0.0,0.0,0.445,1.0,True,wye
3,Load R5,5,0.72750,0.182329,0.0,0.0,0.750,1.0,True,wye
4,Load R6,6,0.54805,0.137354,0.0,0.0,0.565,1.0,True,wye
5,Load R8,8,0.58685,0.147078,0.0,0.0,0.605,1.0,True,wye
6,Load R10,10,0.47530,0.119121,0.0,0.0,0.490,1.0,True,wye
7,Load R11,11,0.32980,0.082656,0.0,0.0,0.340,1.0,True,wye
8,Load R12,12,14.99400,3.044662,0.0,0.0,15.300,1.0,True,wye
9,Load R14,14,0.20855,0.052268,0.0,0.0,0.215,1.0,True,wye
10,Load CI1,1,4.84500,1.592474,0.0,0.0,5.100,1.0,True,wye
11,Load CI3,3,0.22525,0.139597,0.0,0.0,0.265,1.0,True,wye
12,Load CI7,7,0.07650,0.047410,0.0,0.0,0.090,1.0,True,wye
13,Load CI9,9,0.57375,0.355578,0.0,0.0,0.675,1.0,True,wye
14,Load CI10,10,0.06800,0.042143,0.0,0.0,0.080,1.0,True,wye
15,Load CI12,12,5.01600,1.648679,0.0,0.0,5.280,1.0,True,wye
16,Load CI13,13,0.03400,0.021071,0.0,0.0,0.040,1.0,True,wye
17,Load CI14,14,0.33150,0.205445,0.0,0.0,0.390,1.0,True,wye

In [15]:
load_profiles = pd.DataFrame(index=range(24), columns=net.load.index)

In [16]:
for t in range(num_hours):
    load_profiles.loc[t] = net.load['p_mw'].values * load_shape.iloc[t,0]

In [17]:
for h in range(num_hours):
    print(load_shape.iloc[h])

0.28285    0.272295
Name: 0, dtype: float64
0.28285    0.261383
Name: 1, dtype: float64
0.28285    0.261328
Name: 2, dtype: float64
0.28285    0.254316
Name: 3, dtype: float64
0.28285    0.259789
Name: 4, dtype: float64
0.28285    0.272966
Name: 5, dtype: float64
0.28285    0.30915
Name: 6, dtype: float64
0.28285    0.433979
Name: 7, dtype: float64
0.28285    0.542955
Name: 8, dtype: float64
0.28285    0.717333
Name: 9, dtype: float64
0.28285    0.851829
Name: 10, dtype: float64
0.28285    0.864118
Name: 11, dtype: float64
0.28285    0.854116
Name: 12, dtype: float64
0.28285    0.853815
Name: 13, dtype: float64
0.28285    0.852508
Name: 14, dtype: float64
0.28285    0.723452
Name: 15, dtype: float64
0.28285    0.490362
Name: 16, dtype: float64
0.28285    0.428271
Name: 17, dtype: float64
0.28285    0.361402
Name: 18, dtype: float64
0.28285    0.336596
Name: 19, dtype: float64
0.28285    0.328176
Name: 20, dtype: float64
0.28285    0.307331
Name: 21, dtype: float64
0.28285    0.297966
Name: 22, dtype: float64

In [18]:
ds = DFData(load_profiles)

In [19]:
for load_idx in net.load.index:
    ConstControl(net, element='load', variable='p_mw', element_index=load_idx, data_source=ds, profile_name=load_idx)

In [21]:
time_steps = range(num_hours)

In [22]:
ow = OutputWriter(net, time_steps=time_steps, output_path=None)
ow.log_variable('res_bus', 'vm_pu')
ow.log_variable('res_line', 'loading_percent')

In [23]:
run_timeseries(net, time_steps=time_steps)

C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandapower\timeseries\output_writer.py:177: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'range(0, 23)' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  self.output["Parameters"].loc[:, "time_step"] = self.time_steps
C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandapower\control\run_control.py:50: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  level = controller.level.fillna(0).apply(asarray).values
100%|██████████| 23/23 [00:02<00:00, 10.01it/s]

In [24]:
bus_voltages = {}
line_loadings = {}

In [25]:
for t in time_steps:
    bus_voltages[t] = net.res_bus['vm_pu'].values
    line_loadings[t] = net.res_line['loading_percent'].values

In [26]:
df_bus_voltages = pd.DataFrame(bus_voltages)
df_line_loadings = pd.DataFrame(line_loadings)

In [27]:
with pd.ExcelWriter('time_series_results.xlsx') as writer:
    df_bus_voltages.to_excel(writer, sheet_name='Bus_Voltages')
    df_line_loadings.to_excel(writer, sheet_name='Line_Loadings')

print("Results successfully written to time_series_results.xlsx")

Results successfully written to time_series_results.xlsx

In [28]:
net.line

,name,std_type,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,df,parallel,type,in_service
0,Line 1-2,CABLE_CIGRE_MV,1,2,2.82,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
1,Line 2-3,CABLE_CIGRE_MV,2,3,4.42,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
2,Line 3-4,CABLE_CIGRE_MV,3,4,0.61,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
3,Line 4-5,CABLE_CIGRE_MV,4,5,0.56,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
4,Line 5-6,CABLE_CIGRE_MV,5,6,1.54,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
5,Line 7-8,CABLE_CIGRE_MV,7,8,1.67,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
6,Line 8-9,CABLE_CIGRE_MV,8,9,0.32,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
7,Line 9-10,CABLE_CIGRE_MV,9,10,0.77,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
8,Line 10-11,CABLE_CIGRE_MV,10,11,0.33,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
9,Line 3-8,CABLE_CIGRE_MV,3,8,1.30,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
10,Line 12-13,OHL_CIGRE_MV,12,13,4.89,0.510,0.366,10.09679,0.0,0.195,1.0,1,ol,True
11,Line 13-14,OHL_CIGRE_MV,13,14,2.99,0.510,0.366,10.09679,0.0,0.195,1.0,1,ol,True
12,Line 6-7,CABLE_CIGRE_MV,6,7,0.24,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
13,Line 11-4,CABLE_CIGRE_MV,11,4,0.49,0.501,0.716,151.17490,0.0,0.145,1.0,1,cs,True
14,Line 14-8,OHL_CIGRE_MV,14,8,2.00,0.510,0.366,10.09679,0.0,0.195,1.0,1,ol,True

In [29]:
net.res_bus

       vm_pu  va_degree       p_mw    q_mvar
0   1.030000   0.000000 -12.183064  0.000000
1   1.001119 -31.741976   5.402061  4.637136
2   0.990685 -31.843545   0.000000  0.000000
3   0.973796 -31.985016   0.136610  0.208882
4   0.973004 -31.998137   0.117536  0.108182
5   0.972461 -32.007212   0.198095  0.182329
6   0.971827 -32.018209   0.149231  0.137354
7   0.970965 -31.994827   0.020831  0.047410
8   0.971110 -31.995169   0.159796  0.147078
9   0.970612 -31.995043   0.156229  0.355578
10  0.970059 -32.001932   0.147938  0.161264
11  0.969978 -32.003376   0.089803  0.082656
12  1.005628 -31.471043   5.448623  4.693341
13  1.003453 -31.415422   0.009258  0.021071
14  1.002202 -31.383336   0.147053  0.257713

In [30]:
net.res_line.loading_percent

0     2.363409e+01
1     2.404398e+01
2     9.511544e+00
3     7.110598e+00
4     3.057118e+00
5     4.271092e-01
6     8.080888e+00
7     4.879179e+00
8     1.843189e+00
9     1.177976e+01
10    2.306042e+00
11    2.172167e+00
12    0.000000e+00
13    0.000000e+00
14    8.396529e-13
Name: loading_percent, dtype: float64

In [33]:
net

This pandapower network includes the following parameter tables:
   - bus (15 elements)
   - load (18 elements)
   - switch (8 elements)
   - ext_grid (1 element)
   - line (15 elements)
   - trafo (2 elements)
   - controller (18 elements)
   - bus_geodata (15 elements)
   - output_writer (1 element)
 and the following results tables:
   - res_bus (15 elements)
   - res_line (15 elements)
   - res_trafo (2 elements)
   - res_ext_grid (1 element)
   - res_load (18 elements)
   - res_switch (8 elements)

In [34]:
print(net.res_bus)
print(net.res_line)

       vm_pu  va_degree       p_mw    q_mvar
0   1.030000   0.000000 -12.183064  0.000000
1   1.001119 -31.741976   5.402061  4.637136
2   0.990685 -31.843545   0.000000  0.000000
3   0.973796 -31.985016   0.136610  0.208882
4   0.973004 -31.998137   0.117536  0.108182
5   0.972461 -32.007212   0.198095  0.182329
6   0.971827 -32.018209   0.149231  0.137354
7   0.970965 -31.994827   0.020831  0.047410
8   0.971110 -31.995169   0.159796  0.147078
9   0.970612 -31.995043   0.156229  0.355578
10  0.970059 -32.001932   0.147938  0.161264
11  0.969978 -32.003376   0.089803  0.082656
12  1.005628 -31.471043   5.448623  4.693341
13  1.003453 -31.415422   0.009258  0.021071
14  1.002202 -31.383336   0.147053  0.257713
       p_from_mw  q_from_mvar       p_to_mw  q_to_mvar  pl_mw  ql_mvar  \
0   1.176069e+00          0.0 -1.176069e+00        0.0    0.0      0.0
1   1.176069e+00          0.0 -1.176069e+00        0.0    0.0      0.0
2   4.648620e-01          0.0 -4.648620e-01        0.0    0.0      0.0
3   3.473259e-01          0.0 -3.473259e-01        0.0    0.0      0.0
4   1.492313e-01          0.0 -1.492313e-01        0.0    0.0      0.0
5  -2.083057e-02          0.0  2.083057e-02        0.0    0.0      0.0
6   3.939700e-01          0.0 -3.939700e-01        0.0    0.0      0.0
7   2.377408e-01          0.0 -2.377408e-01        0.0    0.0      0.0
8   8.980289e-02          0.0 -8.980289e-02        0.0    0.0      0.0
9   5.745969e-01          0.0 -5.745969e-01        0.0    0.0      0.0
10  1.563109e-01          0.0 -1.563109e-01        0.0    0.0      0.0
11  1.470529e-01          0.0 -1.470529e-01        0.0    0.0      0.0
12  0.000000e+00          0.0 -0.000000e+00        0.0    0.0      0.0
13  0.000000e+00          0.0 -0.000000e+00        0.0    0.0      0.0
14  5.684342e-14          0.0 -5.684342e-14        0.0    0.0      0.0

       i_from_ka       i_to_ka          i_ka  vm_from_pu  va_from_degree  \
0   3.391224e-02  3.426943e-02  3.426943e-02    1.001119      -31.741976
1   3.426943e-02  3.486377e-02  3.486377e-02    0.990685      -31.843545
2   1.378052e-02  1.379174e-02  1.379174e-02    0.973796      -31.985016
3   1.030462e-02  1.031037e-02  1.031037e-02    0.973004      -31.998137
4   4.429930e-03  4.432822e-03  4.432822e-03    0.972461      -32.007212
5   6.193083e-04  6.192160e-04  6.193083e-04    0.970965      -31.994827
6   1.171128e-02  1.171729e-02  1.171729e-02    0.971110      -31.995169
7   7.070784e-03  7.074810e-03  7.074810e-03    0.970612      -31.995043
8   2.672400e-03  2.672624e-03  2.672624e-03    0.970059      -32.001932
9   1.703353e-02  1.708065e-02  1.708065e-02    0.973796      -31.985016
10  4.487054e-03  4.496782e-03  4.496782e-03    1.005628      -31.471043
11  4.230446e-03  4.235726e-03  4.235726e-03    1.003453      -31.415422
12  0.000000e+00  0.000000e+00  0.000000e+00    0.971827      -32.018209
13  0.000000e+00  0.000000e+00  0.000000e+00    0.969978      -32.003376
14  1.637323e-15  1.637319e-15  1.637323e-15    1.002202      -31.383336

    vm_to_pu  va_to_degree  loading_percent
0   0.990685    -31.843545     2.363409e+01
1   0.973796    -31.985016     2.404398e+01
2   0.973004    -31.998137     9.511544e+00
3   0.972461    -32.007212     7.110598e+00
4   0.971827    -32.018209     3.057118e+00
5   0.971110    -31.995169     4.271092e-01
6   0.970612    -31.995043     8.080888e+00
7   0.970059    -32.001932     4.879179e+00
8   0.969978    -32.003376     1.843189e+00
9   0.971110    -31.995169     1.177976e+01
10  1.003453    -31.415422     2.306042e+00
11  1.002202    -31.383336     2.172167e+00
12  0.971828    -32.018248     0.000000e+00
13  0.969982    -32.003540     0.000000e+00
14  1.002204    -31.383521     8.396529e-13